### ISSUE TITLE
Setup problem

### ISSUE THREAD

**Issue by Caibiy** [vickychijwani/quill#143]
FILL THESE DETAILS FIRST:

- App version: <1.3.2>
- Android version: <5.1>
- Device name: <Meizu 4>

----
Hi,guys,i am Chinese student, my english is poor.
I have a problem, I can't solve it, so I hope you can help me, thank you very much. 
I want to learn how you can finish the project 
I follow the guidelines, but I have a problem. 
![problem](https://cloud.githubusercontent.com/assets/16449809/18157266/e6540d0c-704e-11e6-8a6a-6c4a5b354822.png)
![z zdt3 3 6 ja k k4 x7](https://cloud.githubusercontent.com/assets/16449809/18157542/b5602f94-7050-11e6-98dd-34c9d1b38902.png)

How can I solve this problem, please help me, thank you very much.

**Comment by vickychijwani** [comment]
Hi @Caibiy! I have simplified the setup now - all you need to do is `git pull` and build the project in your Android Studio :smile:. Let me know if you have still have problems.

**Comment by Caibiy** [comment]
The problem is solved, thank you very much  : )

**Comment by Caibiy** [comment]
Can you give me some help, how to learn your project.

**Comment by vickychijwani** [comment]
@Caibiy: to be honest this project is not a good one to start learning Android, because it uses several libraries and the code is not very well organized :)

But if you still want to try, I would recommend learning first about how Ghost works. Then you can get an idea of the app architecture by reading [this blog post](http://vickychijwani.me/udacity-android-nanodegree-weeks-3-7/).

Finally you can start exploring the code from [GhostApiService](https://github.com/vickychijwani/quill/blob/master/app/src/main/java/me/vickychijwani/spectre/network/GhostApiService.java), which is the file Retrofit uses to call the Ghost API. [NetworkService](https://github.com/vickychijwani/quill/blob/master/app/src/main/java/me/vickychijwani/spectre/network/NetworkService.java) uses that to fetch data, store it in DB, and answer queries from the UI (I know "NetworkService" is a pretty bad name, this class should be split into smaller classes). The UI makes queries by firing [Otto events](https://github.com/vickychijwani/quill/tree/master/app/src/main/java/me/vickychijwani/spectre/event), which the NetworkService handles.

When you are looking at the code you will have to also explore how these Android libraries work (there are many good online tutorials): Retrofit, Gson, Otto, and Realm.

There is also some documentation in this project's Wiki and many of the issues.

**Comment by vickychijwani** [comment]
@Caibiy: to be honest this project is not a good one to start learning Android, because it uses several libraries and the code is not very well organized :)

But if you still want to try, I would recommend learning first about how Ghost works. Then you can get an idea of the app architecture by reading [this blog post](http://vickychijwani.me/udacity-android-nanodegree-weeks-3-7/).

Finally you can start exploring the code from [GhostApiService](https://github.com/vickychijwani/quill/blob/master/app/src/main/java/me/vickychijwani/spectre/network/GhostApiService.java), which is the file Retrofit uses to call the Ghost API. [NetworkService](https://github.com/vickychijwani/quill/blob/master/app/src/main/java/me/vickychijwani/spectre/network/NetworkService.java) uses that to fetch data, store it in DB, and answer queries from the UI (I know "NetworkService" is a pretty bad name, this class should be split into smaller classes). The UI makes queries by firing [Otto events](https://github.com/vickychijwani/quill/tree/master/app/src/main/java/me/vickychijwani/spectre/event), which the NetworkService handles.

When you are looking at the code you will have to also explore how these Android libraries work (there are many good online tutorials): Retrofit, Gson, Otto, and Realm.

There is also some documentation in this project's Wiki and many of the issues.

**Comment by Caibiy** [comment]
Thank you very much, you are a good person.

**Comment by Caibiy** [comment]
Can you recommend me some learning resources or projects  . 
I am a novice . thank you :)

**Comment by vickychijwani** [comment]
@Caibiy: can you email me? This is not a good place to discuss general learning resources. My email address is in my profile.

**Comment by Caibiy** [comment]
Ok,@vickychijwani  I sent you a email.
