### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by awrelll** [vickychijwani/quill#31]
Hello,
First of all i want to congratulate you! Great app ! Is there a documentation for installing it localy  or use it for my ghost blog?

Thanks!

**Comment by vickychijwani** [comment]
Hey @awrelll, thank you! Quill isn't ready for real users yet. There are some horrible bugs, some important features missing (for example, you can't create new posts at this point; see all the [open issues for 1.0 here](https://github.com/vickychijwani/quill/milestones/1.0)), and I wouldn't recommend that you use it for your blog. That's why there's no documentation at this point (sorry!).

However, if you still want to use it, you can set up the project locally with [Android Studio](http://developer.android.com/tools/studio/index.html) and build the app yourself. It should be quite easy to set up. If you try that and face any issues building it, let me know. I'll be happy to explain further.

**Comment by vickychijwani** [comment]
Closing this issue. Feel free to reopen if there's anything else to discuss.
